Repository wecode-bootcamp-korea/47-2nd-IIIIEE-frontend, pull requests merged in 2023-07, with the labels that each got.

#1 frame layout
  src/Router.js
  src/components/Frame.js
Labels: 멘토 리뷰 요청

#3 [47기 양회진] main page layout
  public/data/mainData.json
  public/data/mainStore.json
  public/images/IMG_7631.jpg
  public/images/IMG_7632.jpg
  public/images/store1.jpeg
  public/images/store2.JPG
  src/Router.js
  src/pages/Main.js
  src/styles/theme.js
Labels: 멘토 리뷰 요청

#5 [47기 양회진] 등록페이지 레이아웃
  package-lock.json
  package.json
  src/Router.js
  src/hooks/useInputValue.js
  src/hooks/useModal.js
  src/hooks/useTag.js
  src/pages/REGISTRATION_DATA.js
  src/pages/Registration.js
Labels: 멘토 리뷰 요청

#4 [47기 최진이] Nav,Filter 레이아웃 구현 완료
  package-lock.json
  package.json
  public/images/logo.png
  src/components/Frame.js
  src/components/Nav.js
  src/components/Nav/FilterBox.js
  src/components/Nav/FilterList.js
  src/components/Nav/Nav.js
  src/components/Nav/NavData/filterBoxData.js
  src/components/Nav/NavData/filterListData.js
  src/pages/Right.js
  src/styles/GlobalStyle.js
  src/styles/theme.js
Labels: 멘토 리뷰 요청

#2 [47기 양회진] 모임정보 및 host 정보 레이아웃
  public/data/host.json
  public/data/text.json
  public/index.html
  src/Router.js
  src/components/Frame.js
  src/components/Host.js
  src/components/Tag.js
  src/pages/Gathering.js
  src/styles/theme.js
Labels: 멘토 리뷰 요청

#6 [47기 최진이]footer layout 완료
  src/Router.js
  src/components/Footer.js
  src/components/Footer/Footer.js
  src/components/Footer/footerdata.js
  src/components/Frame.js
Labels: 멘토 리뷰 요청

#7 [47기 양회진] input 밑에 tag 추가 삭제 기능 구현
  src/Router.js
  src/components/Footer/Footer.js
  src/components/icon/icon.js
  src/components/icon/icon.jsx
  src/pages/Gathering.js
  src/pages/Main.js
  src/pages/REGISTRATION_DATA.js
  src/pages/Registration.js
  src/styles/GlobalStyle.js
Labels: 멘토 리뷰 요청

#11 [47기 양회진] modal control 및 navigate 사용
  src/Router.js
  src/components/Nav/Nav.js
  src/pages/Main.js
Labels: Conflict 해결 요청, 수정 요청

#10 [47기 양회진] 버튼 클릭 시 데이터 저장 및 색 변경 기능 구현
  src/components/icon/svg.js
  src/hooks/useSelectBtn.js
  src/pages/Registration.js
Labels: 멘토 리뷰 요청

#8 [47기 최진이] restaurant info layout
  package-lock.json
  package.json
  public/images/abcdefg.png
  public/images/map.png
  src/Router.js
  src/pages/RestaurantInfo/RestaurantInfo.jsx
  src/pages/RestaurantInfo/RestaurantInfoStyle.js
  src/styles/GlobalStyle.js
Labels: Conflict 해결 요청

#13 [47기 양회진] host list 페이지 레이아웃
  public/data/listData.json
  src/Router.js
  src/components/Nav/Nav.js
  src/pages/HostList/HoseList.js
  src/pages/HostList/HostListStyle.js
Labels: 멘토 리뷰 요청

#12 [47기 양회진] 후기 작성 기능 구현
  src/components/Host.js
  src/pages/Main.js
Labels: 멘토 리뷰 요청

#14 [47기 양회진] 등록페이지 정규표현식 추가 및 id 값 관리
  src/pages/Registration.js
Labels: 멘토 리뷰 요청

#18 [47기 최진이] ADD : 소셜로그인 기능 구현 완료
  .env
  package-lock.json
  public/index.html
  src/Router.js
  src/components/Nav/KakaoLogin.js
  src/components/Nav/Nav.js
  src/styles/GlobalStyle.js
Labels: 멘토 리뷰 요청

#23 [47기 최진이] 필터 메인에만 노출
  src/components/Nav/FilterBox.js
Labels: 멘토 리뷰 요청

#17 [47기 양회진] 후기 API 연결 및 별점 기능 구현
  public/data/host.json
  public/index.html
  src/hooks/useStarRating.js
  src/pages/Gathering/Host.js
  src/pages/Gathering/HostStyle.jsx
Labels: 멘토 리뷰 요청

#25 [47기 양회진] useFetch hook 분리
  public/data/age.json
  public/data/district.json
  public/data/gender.json
  public/data/time.json
  src/hooks/useFetch.js
  src/pages/Main.js
  src/pages/Registration.js
Labels: 멘토 리뷰 요청

#29 [47기 양회진] 종 아이콘 추가
  src/components/icon/icon.js
  src/components/icon/icon.jsx
  src/components/icon/svg.js
  src/pages/Gathering/Gathering.js
  src/pages/Gathering/GatheringStyle.jsx
Labels: 멘토 리뷰 요청

#30 [47기 양회진] 404page
  src/Router.js
  src/pages/NotFound/NotFound.js
  src/pages/NotFound/NotFoundStyle.js
Labels: 멘토 리뷰 요청

#26 [47기 양회진] api 연결
  public/data/gathering.json
  public/data/hostReview.json
  public/data/listData.json
  public/data/text.json
  src/Router.js
  src/components/Nav/Nav.js
  src/components/Tag.js
  src/hooks/useStarRating.js
  src/pages/Gathering/Gathering.js
  src/pages/Gathering/GatheringStyle.jsx
  src/pages/Gathering/Host.js
  src/pages/HostList/HoseList.js
  src/pages/Registration.js
Labels: 멘토 리뷰 요청

#31 [47기 양회진] 카카오페이 결제 api 연결
  public/data/listData.json
  src/Router.js
  src/pages/Gathering/Gathering.js
  src/pages/Gathering/Host.js
  src/pages/HostList/HoseList.js
  src/pages/HostList/KakaoPay.js
  src/pages/HostList/PayFail.js
  src/pages/HostList/PayFailStyle.jsx
Labels: 멘토 리뷰 요청

#28 [47기 양회진] 폼데이터 사용해서 이미지 업로드
  public/data/age.json
  public/data/hostReview.json
  src/Router.js
  src/pages/Gathering/Host.js
  src/pages/Registration/Registration.js
  src/pages/Registration/RegistrationStyle.jsx
Labels: 수정 요청

#27 [47기 최진이] 필터링된된 값 url에 쿼리 추가
  package-lock.json
  package.json
  src/components/Nav/FilterBox.js
  src/components/Nav/FilterList.js
  src/components/Nav/Nav.js
  src/components/Nav/NavData/filterBoxData.js
  src/components/Nav/NavData/filterListData.js
  src/pages/GestList/GestListStyle.js
  src/pages/Main.js
Labels: 멘토 리뷰 요청

#34 [47기 최진이] main페이지 필터링 구현 완료
  src/components/Nav/FilterBox.js
  src/components/Nav/FilterList.js
  src/components/Nav/Nav.js
  src/pages/Main.js
Labels: 멘토 리뷰 요청

#35 [47기 최진이] 맛집상세페이지 useParams구현
  src/Router.js
  src/components/Map.jsx
  src/components/Nav/FilterBox.js
  src/components/Nav/FilterList.js
  src/components/Nav/KakaoLogin.js
  src/components/Nav/Nav.js
  src/components/Slide/Slide.jsx
  src/hooks/useRequireAuth.js
  src/pages/Gathering/Gathering.js
  src/pages/Gathering/Host.js
  src/pages/GestList/GestList.jsx
  src/pages/HostList/HoseList.js
  src/pages/Main.js
  src/pages/Registration/Registration.js
  src/pages/RestaurantInfo/RestaurantInfo.jsx
Labels: 멘토 리뷰 요청

#36 [47기 양회진] connection api
  src/Router.js
  src/components/Nav/KakaoLogin.js
  src/hooks/useStarRating.js
  src/pages/Gathering/Gathering.js
  src/pages/Gathering/GatheringStyle.jsx
  src/pages/Gathering/Host.js
  src/pages/Gathering/HostStyle.jsx
  src/pages/HostList/HoseList.js
  src/pages/HostList/HostListStyle.js
  src/pages/HostList/KakaoPay.js
  src/pages/Main.js
  src/pages/Registration/Registration.js
Labels: 멘토 리뷰 요청
